import { Component } from '@angular/core';


export interface SubdivisionData {
  subdivision: string;
  district: string;
  abbreviation: string;
}

@Component({
  selector: 'app-about-section-help-index',
  templateUrl: './about-section-help-index.component.html',
  styleUrls: ['./about-section-help-index.component.css']
})
export class AboutSectionHelpIndexComponent {

  displayedColumns: string[] = ['subdivision', 'district', 'abbreviation'];

  subdivisions: SubdivisionData[] = [
    { subdivision: 'A & N ISLAND', district: 'NICOBAR', abbreviation: 'NCB' },
    { subdivision: '', district: 'NORTH & MIDDLE ANDAMAN', abbreviation: 'NMA' },
    { subdivision: '', district: 'SOUTH ANDAMAN', abbreviation: 'SAN' },
    { subdivision: 'ARUNACHAL PRADESH', district: 'ANJAW', abbreviation: 'ANJ' },
    { subdivision: '', district: 'CHANGLANG', abbreviation: 'CHA' },
    { subdivision: '', district: 'DIBANG VALLEY', abbreviation: 'DIV' },

    { subdivision: 'ASSAM & MEGHALAYA', district: 'BAKSA', abbreviation: 'BKS' },
    { subdivision: '', district: 'BARPETA', abbreviation: 'BPT' },
    { subdivision: '', district: 'BONGAIGAON', abbreviation: 'BNG' },
    { subdivision: '', district: 'CACHAR', abbreviation: 'CHR' },
    { subdivision: '', district: 'CHIRANG', abbreviation: 'CRG' },
    { subdivision: '', district: 'DARRANG', abbreviation: 'DRG' },
    { subdivision: '', district: 'DHEMAJI', abbreviation: 'DMJ' },
    { subdivision: '', district: 'DHUBRI', abbreviation: 'DBB' },
    { subdivision: '', district: 'DIBRUGARH', abbreviation: 'DBR' },
    { subdivision: '', district: 'EAST GARO HILLS', abbreviation: 'EGH' },
    { subdivision: '', district: 'EAST KHASI HILLS', abbreviation: 'EKH' },
    { subdivision: '', district: 'GOALPARA', abbreviation: 'GLP' },
    { subdivision: '', district: 'GOLAGHAT', abbreviation: 'GLT' },
    { subdivision: '', district: 'HAILAKANDI', abbreviation: 'HLK' },
    { subdivision: '', district: 'JAINTIA HILLS', abbreviation: 'JNH' },
    { subdivision: '', district: 'JORHAT', abbreviation: 'JHT' },
    { subdivision: '', district: 'KAMRUP METRO', abbreviation: 'KRM' },
    { subdivision: '', district: 'KAMRUP RURAL', abbreviation: 'KMP' },
    { subdivision: '', district: 'KARBI ANALOG', abbreviation: 'KAG' },
    { subdivision: '', district: 'KARIMGANJ', abbreviation: 'KGJ' },
    { subdivision: '', district: 'KOKRAJHAR', abbreviation: 'KJR' },
    { subdivision: '', district: 'LAKHIMPUR', abbreviation: 'LKR' },
    { subdivision: '', district: 'MORIGAON', abbreviation: 'MRG' },
    { subdivision: '', district: 'N.C HILLS', abbreviation: 'NCH' },
    { subdivision: '', district: 'NAGAON', abbreviation: 'NGN' },
    { subdivision: '', district: 'NALBARI', abbreviation: 'NLB' },
    { subdivision: '', district: 'RI BHOI', abbreviation: 'RIB' },
    { subdivision: '', district: 'SIBSAGAR', abbreviation: 'SBR' },
    { subdivision: '', district: 'SONITPUR', abbreviation: 'SPR' },
    { subdivision: '', district: 'SOUTH GARO HILLS', abbreviation: 'SGH' },
    { subdivision: '', district: 'TINSUKIA', abbreviation: 'TSK' },
    { subdivision: '', district: 'UDALGURI', abbreviation: 'UDG' },
    { subdivision: '', district: 'WEST GARO HILLS', abbreviation: 'WGH' },
    { subdivision: '', district: 'WEST KHASI HILLS', abbreviation: 'WKH' },

    { subdivision: '', district: 'ARWAL', abbreviation: 'ARW' },
    { subdivision: 'BIHAR', district: 'ARARIYA', abbreviation: 'ARR' },
    { subdivision: '', district: 'AURANGABAD', abbreviation: 'ND' },
    { subdivision: '', district: 'BANKA', abbreviation: 'BNK' },
    { subdivision: '', district: 'BEGUSARAI', abbreviation: 'BGS' },
    { subdivision: '', district: 'BHABUA', abbreviation: 'BBU' },
    { subdivision: '', district: 'BHAGALPUR', abbreviation: 'BGP' },
    { subdivision: '', district: 'BHOJPUR', abbreviation: 'BJR' },
    { subdivision: '', district: 'BUXAR', abbreviation: 'BXR' },
    { subdivision: '', district: 'DRABHANGA', abbreviation: 'DBG' },
    { subdivision: '', district: 'GAYA', abbreviation: 'GYA' },
    { subdivision: '', district: 'GOPALGANJ', abbreviation: 'GPG' },
    { subdivision: '', district: 'JAHANABAD', abbreviation: 'JBD' },
    { subdivision: '', district: 'JAMUI', abbreviation: 'JMI' },
    { subdivision: '', district: 'KATIHAR', abbreviation: 'KTH' },
    { subdivision: '', district: 'KHAGARIA', abbreviation: 'KHA' },
    { subdivision: '', district: 'KISHANGANJ', abbreviation: 'KIS' },
    { subdivision: '', district: 'LAKHISARAI', abbreviation: 'LKS' },
    { subdivision: '', district: 'MADHEPURA', abbreviation: 'MDP' },
    { subdivision: '', district: 'MADUBANI', abbreviation: 'MDB' },
    { subdivision: '', district: 'MUNGER', abbreviation: 'MGR' },
    { subdivision: '', district: 'MUZAFFARPUR', abbreviation: 'MZF' },
    { subdivision: '', district: 'NALANDA', abbreviation: 'NLD' },
    { subdivision: '', district: 'NAWADA', abbreviation: 'NWD' },
    { subdivision: '', district: 'PACHIM CHAMPARAN', abbreviation: 'CPW' },
    { subdivision: '', district: 'PATNA', abbreviation: 'PTN' },
    { subdivision: '', district: 'PURBA CHAMPARAN', abbreviation: 'CPE' },
    { subdivision: '', district: 'PURNIA', abbreviation: 'PRN' },
    { subdivision: '', district: 'ROHTAS', abbreviation: 'RTS' },
    { subdivision: '', district: 'SAHARSA', abbreviation: 'SAH' },
    { subdivision: '', district: 'SAMASTIPUR', abbreviation: 'SAM' },
    { subdivision: '', district: 'SARAN', abbreviation: 'SAR' },
    { subdivision: '', district: 'SHEIKHPURA', abbreviation: 'SKP' },
    { subdivision: '', district: 'SHEOHAR', abbreviation: 'SHR' },
    { subdivision: '', district: 'SITAMARHI', abbreviation: 'SIT' },
    { subdivision: '', district: 'SIWAN', abbreviation: 'SWN' },
    { subdivision: '', district: 'SUPAUL', abbreviation: 'SPL' },

      { subdivision: 'CHHATTISGARH', district: 'BASTAR', abbreviation: 'BTR' },
      { subdivision: '', district: 'BIJAPUR', abbreviation: 'ND' },
      { subdivision: '', district: 'BILASPUR', abbreviation: 'ND' },
      { subdivision: '', district: 'DANTEWARA', abbreviation: 'DTW' },
      { subdivision: '', district: 'DHAMTARI', abbreviation: 'DTR' },
      { subdivision: '', district: 'DURG', abbreviation: 'DUR' },
      { subdivision: '', district: 'JANJGIR_CHAMPA', abbreviation: 'JJG' },
      { subdivision: '', district: 'JASHPUR', abbreviation: 'JHP' },
      { subdivision: '', district: 'KANKER', abbreviation: 'KNK' },
      { subdivision: '', district: 'KAWARDHA', abbreviation: 'ND' },
      { subdivision: '', district: 'KORBA', abbreviation: 'KRB' },
      { subdivision: '', district: 'KOREA', abbreviation: 'KRY' },
      { subdivision: '', district: 'MAHASAMUND', abbreviation: 'MMD' },
      { subdivision: '', district: 'NARAYANPUR', abbreviation: 'NNP' },
      { subdivision: '', district: 'RAIGARH', abbreviation: 'ND' },
      { subdivision: '', district: 'RAIPUR', abbreviation: 'RPR' },
      { subdivision: '', district: 'RAJNANDGAON', abbreviation: 'RNG' },
      { subdivision: '', district: 'SURGUJA', abbreviation: 'SRG' },
      
      { subdivision: 'COASTAL ANDHRA PRADESH', district: 'EAST GODAVARI', abbreviation: 'EGV' },
      { subdivision: '', district: 'GUNTUR', abbreviation: 'GTR' },
      { subdivision: '', district: 'KRISHNA', abbreviation: 'KRN' },
      { subdivision: '', district: 'NELLORE', abbreviation: 'NLR' },
      { subdivision: '', district: 'PRAKASAM', abbreviation: 'PKM' },
      { subdivision: '', district: 'SRIKAKULAM', abbreviation: 'SKM' },
      { subdivision: '', district: 'VISHAKHAPATNAM', abbreviation: 'VSM' },
      { subdivision: '', district: 'VIZIANAGARAM', abbreviation: 'VZM' },
      { subdivision: '', district: 'WEST GODAVARI', abbreviation: 'WGV' },
      
      { subdivision: 'COASTAL KARNATAKA', district: 'DAKSHIN KANNADA', abbreviation: 'DKN' },
      { subdivision: '', district: 'UDUPI', abbreviation: 'UDU' },
      { subdivision: '', district: 'UTTAR KANNADA', abbreviation: 'UKN' },
      
      { subdivision: 'EAST MADHYA PRADESH', district: 'ANUPPUR', abbreviation: 'ANP' },
      { subdivision: '', district: 'BALAGHAT', abbreviation: 'BLG' },
      { subdivision: '', district: 'CHHATARPUR', abbreviation: 'CTP' },
      { subdivision: '', district: 'CHHINDWARA', abbreviation: 'CDW' },
      { subdivision: '', district: 'DAMOH', abbreviation: 'DMH' },
      { subdivision: '', district: 'DINDORI', abbreviation: 'DDR' },
      { subdivision: '', district: 'JABALPUR', abbreviation: 'JBP' },
      { subdivision: '', district: 'KATNI', abbreviation: 'KTN' },
      { subdivision: '', district: 'MANDLA', abbreviation: 'MDL' },
      { subdivision: '', district: 'NARSHIMAPURA', abbreviation: 'NSP' },
      { subdivision: '', district: 'PANNA', abbreviation: 'PAN' },
      { subdivision: '', district: 'REWA', abbreviation: 'RWA' },
      { subdivision: '', district: 'SAGAR', abbreviation: 'SAG' },
      { subdivision: '', district: 'SATNA', abbreviation: 'STN' },
      { subdivision: '', district: 'SEONI', abbreviation: 'SNI' },
      { subdivision: '', district: 'SHAHDOL', abbreviation: 'SHD' },
      { subdivision: '', district: 'SIDHI', abbreviation: 'SDH' },
      { subdivision: '', district: 'SINGRAULI', abbreviation: 'SRL' },
      { subdivision: '', district: 'TIKAMGARH', abbreviation: 'TKM' },
      { subdivision: '', district: 'UMARIA', abbreviation: 'UMR' },
      
      { subdivision: 'EAST RAJASTHAN', district: 'AJMER', abbreviation: 'AJM' },
      { subdivision: '', district: 'ALWAR', abbreviation: 'ALW' },
      { subdivision: '', district: 'BANSWARA', abbreviation: 'BSW' },
      { subdivision: '', district: 'BARAN', abbreviation: 'BRN' },
      { subdivision: '', district: 'BHARATPUR', abbreviation: 'BTP' },
      { subdivision: '', district: 'BHILWARA', abbreviation: 'BLW' },
      { subdivision: '', district: 'BUNDI', abbreviation: 'BDI' },
      { subdivision: '', district: 'CHITTAURGARH', abbreviation: 'CTG' },
      { subdivision: '', district: 'DAUSA', abbreviation: 'DSA' },
      { subdivision: '', district: 'DHOLPUR', abbreviation: 'DLP' },
      { subdivision: '', district: 'DUNGARPUR', abbreviation: 'DGP' },
      { subdivision: '', district: 'JAIPUR', abbreviation: 'JPR' },
      { subdivision: '', district: 'JHALAWAR', abbreviation: 'JLW' },
      { subdivision: '', district: 'JHUNJHUNUN', abbreviation: 'JJN' },
      { subdivision: '', district: 'KARAULI', abbreviation: 'KRA' },
      { subdivision: '', district: 'KOTA', abbreviation: 'KTA' },
      { subdivision: '', district: 'PRATAPGARH', abbreviation: 'ND' },
      { subdivision: '', district: 'RAJSMAND', abbreviation: 'RSM' },
      { subdivision: '', district: 'SIKAR', abbreviation: 'SKR' },
      { subdivision: '', district: 'SIROHI', abbreviation: 'SRH' },
      { subdivision: '', district: 'SWAIMADHOPUR', abbreviation: 'SAW' },
      { subdivision: '', district: 'TONK', abbreviation: 'TNK' },
      { subdivision: '', district: 'UDAIPUR', abbreviation: 'UDP' },
    
      { subdivision: 'EAST UTTAR PRADESH', district: 'ALLAHABAD', abbreviation: 'AHB' },
  { subdivision: '', district: 'AMBEDKARNAGAR', abbreviation: 'ABN' },
  { subdivision: '', district: 'AMETHI', abbreviation: 'ND' },
  { subdivision: '', district: 'AZAMGARH', abbreviation: 'AZG' },
  { subdivision: '', district: 'BAHRAICH', abbreviation: 'BRC' },
  { subdivision: '', district: 'BALLIA', abbreviation: 'BAL' },
  { subdivision: '', district: 'BALRAMPUR', abbreviation: 'BRP' },
  { subdivision: '', district: 'BANDA', abbreviation: 'BNA' },
  { subdivision: '', district: 'BARABANKI', abbreviation: 'BBK' },
  { subdivision: '', district: 'BASTI', abbreviation: 'BST' },
  { subdivision: '', district: 'CHANDAULI', abbreviation: 'CND' },
  { subdivision: '', district: 'CHITRAKOOT', abbreviation: 'ND' },
  { subdivision: '', district: 'DEORIA', abbreviation: 'DOR' },
  { subdivision: '', district: 'FAIZABAD', abbreviation: 'FAI' },
  { subdivision: '', district: 'FARRUKHABAD', abbreviation: 'FKB' },
  { subdivision: '', district: 'FATEHPUR', abbreviation: 'FTP' },
  { subdivision: '', district: 'GAZIPUR', abbreviation: 'GZP' },
  { subdivision: '', district: 'GONDA', abbreviation: 'GND' },
  { subdivision: '', district: 'GORAKHPUR', abbreviation: 'GRP' },
  { subdivision: '', district: 'HARDOI', abbreviation: 'HDO' },
  { subdivision: '', district: 'JAUNPUR', abbreviation: 'JNP' },
  { subdivision: '', district: 'KANNAUJ', abbreviation: 'KNA' },
  { subdivision: '', district: 'KANPUR', abbreviation: 'KPC' },
  { subdivision: '', district: 'KANPUR DEHAT', abbreviation: 'KPD' },
  { subdivision: '', district: 'KAUSHAMBI', abbreviation: 'KSM' },
  { subdivision: '', district: 'KHERI', abbreviation: 'KRI' },
  { subdivision: '', district: 'KUSHINAGAR', abbreviation: 'KSN' },
  { subdivision: '', district: 'LACKNOW', abbreviation: 'LNO' },
  { subdivision: '', district: 'MAHARAJGANJ', abbreviation: 'MHG' },
  { subdivision: '', district: 'MAU', abbreviation: 'MAU' },
  { subdivision: '', district: 'MIRZAPUR', abbreviation: 'MZP' },
  { subdivision: '', district: 'PRATAPGARH', abbreviation: 'ND' },
  { subdivision: '', district: 'RAIBEARELI', abbreviation: 'RBL' },
  { subdivision: '', district: 'SANTKABIRNAGAR', abbreviation: 'SKN' },
  { subdivision: '', district: 'SANTRAVIDASNAGAR', abbreviation: 'SRV' },
  { subdivision: '', district: 'SHRAWASTI', abbreviation: 'SRW' },
  { subdivision: '', district: 'SIDDHARTHNAGAR', abbreviation: 'SDN' },
  { subdivision: '', district: 'SITAPUR', abbreviation: 'STP' },
  { subdivision: '', district: 'SONBHADRA', abbreviation: 'SBD' },
  { subdivision: '', district: 'SULTANPUR', abbreviation: 'SUL' },
  { subdivision: '', district: 'UNNAO', abbreviation: 'UNN' },
  { subdivision: '', district: 'VARANASI', abbreviation: 'VRN' },

  { subdivision: 'GANGETIC WEST BENGAL', district: 'BANKURA', abbreviation: 'BKR' },
  { subdivision: '', district: 'BARDAMAN', abbreviation: 'BDN' },
  { subdivision: '', district: 'BIRBHUM', abbreviation: 'BBM' },
  { subdivision: '', district: 'EASTMEDNIPUR', abbreviation: 'EMP' },
  { subdivision: '', district: 'HAORA', abbreviation: 'HRA' },
  { subdivision: '', district: 'HUGLI', abbreviation: 'HGL' },
  { subdivision: '', district: 'MURSIDABAD', abbreviation: 'MBD' },
  { subdivision: '', district: 'NADIA', abbreviation: 'NDA' },
  { subdivision: '', district: 'NORTH 24 PRAGANA', abbreviation: 'NPG' },
  { subdivision: '', district: 'PASHCHIM MEDINIPUR', abbreviation: 'WMP' },
  { subdivision: '', district: 'PURULIYA', abbreviation: 'PRL' },
  { subdivision: '', district: 'SOUTH 24 PARGANAS', abbreviation: 'SPG' },

  { subdivision: 'GUJARAT REGION', district: 'AHMADABAD', abbreviation: 'AMD' },
  { subdivision: '', district: 'ANAND', abbreviation: 'AND' },
  { subdivision: '', district: 'BANASKANTHA', abbreviation: 'BAN' },
  { subdivision: '', district: 'BHARUCH', abbreviation: 'BRH' },
  { subdivision: '', district: 'DADAR & NAGAR HAVELI', abbreviation: 'DNV' },
  { subdivision: '', district: 'DAHOD', abbreviation: 'DHD' },
  { subdivision: '', district: 'DAMAN', abbreviation: 'DMN' },
  { subdivision: '', district: 'DANGS', abbreviation: 'DNG' },
  { subdivision: '', district: 'GANDHINAGAR', abbreviation: 'GNR' },
  { subdivision: '', district: 'KHERA', abbreviation: 'KDA' },
  { subdivision: '', district: 'MAHESANA', abbreviation: 'MSN' },
  { subdivision: '', district: 'NARMADA', abbreviation: 'NMD' },
  { subdivision: '', district: 'NAVSARI', abbreviation: 'NAV' },
  { subdivision: '', district: 'PANCHMAHAL', abbreviation: 'PML' },
  { subdivision: '', district: 'PATAN', abbreviation: 'PAT' },
  { subdivision: '', district: 'SABAR KANTHA', abbreviation: 'SBK' },
  { subdivision: '', district: 'SURAT', abbreviation: 'SRT' },
  { subdivision: '', district: 'TAPI', abbreviation: 'TPI' },
  { subdivision: '', district: 'VADODARA', abbreviation: 'ND' },
  { subdivision: '', district: 'VALSAD', abbreviation: 'VLD' },

  { subdivision: 'HAR. CHD & DELHI', district: 'AMBALA', abbreviation: 'AMB' },
  { subdivision: '', district: 'BHIWANI', abbreviation: 'BWN' },
  { subdivision: '', district: 'CENTRAL DELHI', abbreviation: 'CDL' },
  { subdivision: '', district: 'CHANDIGARH', abbreviation: 'CHD' },
  { subdivision: '', district: 'EAST DELHI', abbreviation: 'EDL' },
  { subdivision: '', district: 'FARIDABAD', abbreviation: 'FBD' },
  { subdivision: '', district: 'FATEHABAD', abbreviation: 'FTB' },
  { subdivision: '', district: 'GURGAON', abbreviation: 'GUR' },
  { subdivision: '', district: 'HISAR', abbreviation: 'HSR' },
  { subdivision: '', district: 'JHAJJAR', abbreviation: 'JJR' },
  { subdivision: '', district: 'JIND', abbreviation: 'JND' },
  { subdivision: '', district: 'KAITHAL', abbreviation: 'KTL' },
  { subdivision: '', district: 'KARNAL', abbreviation: 'KNL' },
  { subdivision: '', district: 'KURUKSHETRA', abbreviation: 'KKR' },
  { subdivision: '', district: 'MAHENDRAGARH', abbreviation: 'MHN' },
  { subdivision: '', district: 'MEWAT', abbreviation: 'MWT' },
  { subdivision: '', district: 'NORTH DELHI', abbreviation: 'NDL' },
  { subdivision: '', district: 'NORTH EAST DELHI', abbreviation: 'NDE' },
  { subdivision: '', district: 'NORTH WEST DELHI', abbreviation: 'NDW' },
  { subdivision: '', district: 'PALWAL', abbreviation: 'PLW' },
  { subdivision: '', district: 'PANCHKULA', abbreviation: 'PKL' },
  { subdivision: '', district: 'PANIPAT', abbreviation: 'PNP' },
  { subdivision: '', district: 'REWARI', abbreviation: 'RWR' },
  { subdivision: '', district: 'ROHTAK', abbreviation: 'RTK' },
  { subdivision: '', district: 'SIRSA', abbreviation: 'SRS' },
  { subdivision: '', district: 'SONIPAT', abbreviation: 'SNP' },
  { subdivision: '', district: 'SOUTH DELHI', abbreviation: 'SDL'},
  { subdivision: '', district: 'WEST DELHI', abbreviation: 'WDL'},
  { subdivision: '', district: 'YAMUNANAGAR', abbreviation: 'YNR'},

  { subdivision: 'HIMACHAL PRADESH', district: 'BILASPUR', abbreviation: 'ND' },
  { subdivision: '', district: 'CHAMBA', abbreviation: 'CHB' },
  { subdivision: '', district: 'HAMIRPUR', abbreviation: 'ND' },
  { subdivision: '', district: 'KANGRA', abbreviation: 'KGR' },
  { subdivision: '', district: 'KINNAUR', abbreviation: 'KNR' },
  { subdivision: '', district: 'KULLU', abbreviation: 'KLU' },
  { subdivision: '', district: 'LAHUL&SPITI', abbreviation: 'LSP' },
  { subdivision: '', district: 'MANDI', abbreviation: 'MND' },
  { subdivision: '', district: 'SHIMLA', abbreviation: 'SML' },
  { subdivision: '', district: 'SIRMAUR', abbreviation: 'SMR' },
  { subdivision: '', district: 'SOLAN', abbreviation: 'SLN' },
  { subdivision: '', district: 'UNA', abbreviation: 'UNA' },

  { subdivision: 'JAMMU & KASHMIR', district: 'ANANTNAG', abbreviation: 'ATN' },
  { subdivision: '', district: 'BARAMULA', abbreviation: 'BLA' },
  { subdivision: '', district: 'CHILAS', abbreviation: 'ND' },
  { subdivision: '', district: 'GILGIT', abbreviation: 'ND' },
  { subdivision: '', district: 'JAMMU', abbreviation: 'JAM' },
  { subdivision: '', district: 'KATHUA', abbreviation: 'KUA' },
  { subdivision: '', district: 'LEH AND LADAKH', abbreviation: 'LEH' },
  { subdivision: '', district: 'PUNCH', abbreviation: 'PCH' },
  { subdivision: '', district: 'RIASI', abbreviation: 'RSI' },
  { subdivision: '', district: 'TRIBAL TERRITORY', abbreviation: 'ND' },
  { subdivision: '', district: 'UDHAMPUR', abbreviation: 'UDM' },

  { subdivision: 'JAMMU AND KASHMIR', district: 'GILGIT WAZARAT', abbreviation: 'ND' },
  { subdivision: '', district: 'MIRPUR', abbreviation: 'ND' },
  { subdivision: '', district: 'MUZAFFARABAD', abbreviation: 'ND' },

  { subdivision: 'JHARKHAND', district: 'BOKARO', abbreviation: 'BOK' },
  { subdivision: '', district: 'CHATRA', abbreviation: 'CTR' },
  { subdivision: '', district: 'DEVGARH', abbreviation: 'DGH' },
  { subdivision: '', district: 'DHANBAD', abbreviation: 'DBD' },
  { subdivision: '', district: 'DUMKA', abbreviation: 'DMK' },
  { subdivision: '', district: 'GARHWA', abbreviation: 'GRH' },
  { subdivision: '', district: 'GIRIDIH', abbreviation: 'GRD' },
  { subdivision: '', district: 'GOODA', abbreviation: 'GDA' },
  { subdivision: '', district: 'GUMLA', abbreviation: 'GML' },
  { subdivision: '', district: 'HAZARIBAGH', abbreviation: 'HZB' },
  { subdivision: '', district: 'JAMTARA', abbreviation: 'JTR' },
  { subdivision: '', district: 'KHUNTI', abbreviation: 'KNT' },
  { subdivision: '', district: 'KODARMA', abbreviation: 'KDR' },
  { subdivision: '', district: 'LATEHAR', abbreviation: 'LTH' },
  { subdivision: '', district: 'LOHARDAGA', abbreviation: 'LHD' },
  { subdivision: '', district: 'PAKUR', abbreviation: 'PKR' },
  { subdivision: '', district: 'PALAMU', abbreviation: 'PLM' },
  { subdivision: '', district: 'PASCHIM SINGHBHUMI', abbreviation: 'ND' },
  { subdivision: '', district: 'PURBI SINGBHUMI', abbreviation: 'ND' },
  { subdivision: '', district: 'RAMGARH', abbreviation: 'RMG' },
  { subdivision: '', district: 'RANCHI', abbreviation: 'RNC' },
  { subdivision: '', district: 'SAHEBGANJ', abbreviation: 'SBG' },
  { subdivision: '', district: 'SARAIKELA', abbreviation: 'SKW' },
  { subdivision: '', district: 'SIMDEGA', abbreviation: 'SMD' },

  { subdivision: 'KERALA', district: 'ALAPPUZHA', abbreviation: 'APZ' },
  { subdivision: '', district: 'ERNAKULAM', abbreviation: 'ENK' },
  { subdivision: '', district: 'IDUKKI', abbreviation: 'IDK' },
  { subdivision: '', district: 'KANNUR', abbreviation: 'ND' },
  { subdivision: '', district: 'KASARGOD', abbreviation: 'KSG' },
  { subdivision: '', district: 'KOLLAM', abbreviation: 'KLM' },
  { subdivision: '', district: 'KOTTYAM', abbreviation: 'KOT' },
  { subdivision: '', district: 'KOZIKOD', abbreviation: 'KZK' },
  { subdivision: '', district: 'MALAPPURAM', abbreviation: 'MPM' },
  { subdivision: '', district: 'PALAKKAD', abbreviation: 'PLK' },
  { subdivision: '', district: 'PATTANAMITTIA', abbreviation: 'PTM' },
  { subdivision: '', district: 'THIRUVANANTHPURAM', abbreviation: 'TRM' },
  { subdivision: '', district: 'TRISHUR', abbreviation: 'THR' },
  { subdivision: '', district: 'WAYANAD', abbreviation: 'ND' },

  { subdivision: 'KONKAN & GOA', district: 'MUMBAI CITY', abbreviation: 'MBC' },
  { subdivision: '', district: 'NORTH GOA', abbreviation: 'GON' },
  { subdivision: '', district: 'RAIGARH', abbreviation: 'ND' },
  { subdivision: '', district: 'RATNAGIRI', abbreviation: 'RTG' },
  { subdivision: '', district: 'SINDHUDURG', abbreviation: 'SDG' },
  { subdivision: '', district: 'SOUTH GOA', abbreviation: 'GOS' },
  { subdivision: '', district: 'SUBURBAN MUMBAI', abbreviation: 'ND' },
  { subdivision: '', district: 'THANE', abbreviation: 'THN' },

  { subdivision: 'LAKSHADWEEP', district: 'KAVARATTI', abbreviation: 'ND' },
  { subdivision: '', district: 'LAKSHADWEEP', abbreviation: 'LKD' },

  { subdivision: 'MADHYA MAHARASHTRA', district: 'AHMADNAGAR', abbreviation: 'ANG' },
  { subdivision: '', district: 'DHULE', abbreviation: 'DHL' },
  { subdivision: '', district: 'JALGAON', abbreviation: 'JLG' },
  { subdivision: '', district: 'KOLHAPUR', abbreviation: 'KLP' },
  { subdivision: '', district: 'NANDURBAR', abbreviation: 'NDB' },
  { subdivision: '', district: 'NASIK', abbreviation: 'NSK' },
  { subdivision: '', district: 'PUNE', abbreviation: 'PNA' },
  { subdivision: '', district: 'SANGLI', abbreviation: 'SNG' },
  { subdivision: '', district: 'SATARA', abbreviation: 'STR' },
  { subdivision: '', district: 'SOLAPUR', abbreviation: 'SLR' },

  { subdivision: 'MARATHWADA', district: 'AURANGABAD', abbreviation: 'ND' },
  { subdivision: '', district: 'BID', abbreviation: 'BED' },
  { subdivision: '', district: 'HINGOLI', abbreviation: 'HIN' },
  { subdivision: '', district: 'JALNA', abbreviation: 'JLN' },
  { subdivision: '', district: 'LATUR', abbreviation: 'LTR' },
  { subdivision: '', district: 'NANDED', abbreviation: 'NDD' },
  { subdivision: '', district: 'OSMANABAD', abbreviation: 'OBD' },
  { subdivision: '', district: 'PARBHANI', abbreviation: 'PBN' },

  { subdivision: 'N M M T', district: 'AIZAWL', abbreviation: 'AZW' },
  { subdivision: '', district: 'BISHNUPUR', abbreviation: 'BPR' },
  { subdivision: '', district: 'CHAMPHAI', abbreviation: 'CPI' },
  { subdivision: '', district: 'CHANDEL', abbreviation: 'CNL' },
  { subdivision: '', district: 'CHURACHANDPUR', abbreviation: 'CCP' },
  { subdivision: '', district: 'DHALAI', abbreviation: 'DLI' },
  { subdivision: '', district: 'DIMAPUR', abbreviation: 'DPR' },
  { subdivision: '', district: 'IMPHAL EAST', abbreviation: 'IME' },
  { subdivision: '', district: 'IMPHAL WEST', abbreviation: 'IMW' },
  { subdivision: '', district: 'KIPHIRE', abbreviation: 'KPR' },
  { subdivision: '', district: 'KOHIMA', abbreviation: 'KMA' },
  { subdivision: '', district: 'KOLASIB', abbreviation: 'KSB' },
  { subdivision: '', district: 'LAWNGTLAI', abbreviation: 'LGT' },
  { subdivision: '', district: 'LONGLENG', abbreviation: 'LGL' },
  { subdivision: '', district: 'LUNGLEI', abbreviation: 'LLI' },
  { subdivision: '', district: 'MAMIT', abbreviation: 'MMT' },
  { subdivision: '', district: 'MOKOKCHUNG', abbreviation: 'MKK' },
  { subdivision: '', district: 'MON', abbreviation: 'MON' },
  { subdivision: '', district: 'NORTH TRIPURA', abbreviation: 'TRN' },
  { subdivision: '', district: 'PEREN', abbreviation: 'PAR' },
  { subdivision: '', district: 'PHEK', abbreviation: 'PHK' },
  { subdivision: '', district: 'SAIHA', abbreviation: 'SHA' },
  { subdivision: '', district: 'SENAPATI', abbreviation: 'SPT' },
  { subdivision: '', district: 'SERCHHIP', abbreviation: 'SRC' },
  { subdivision: '', district: 'SOUTH TRIPURA', abbreviation: 'TRS' },
  { subdivision: '', district: 'TAMENGLONG', abbreviation: 'TAM' },
  { subdivision: '', district: 'THOUBAL', abbreviation: 'TBL' },
  { subdivision: '', district: 'TUENSANG', abbreviation: 'TSG' },
  { subdivision: '', district: 'UKHRUL', abbreviation: 'UKL' },
  { subdivision: '', district: 'WEST TRIPURA', abbreviation: 'TRW' },
  { subdivision: '', district: 'WOKHA', abbreviation: 'WOK' },
  { subdivision: '', district: 'ZUNHEBOTO', abbreviation: 'ZTO' },

  { subdivision: 'N M M T', district: 'IMPHAL EAST', abbreviation: 'IME' },

  { subdivision: 'N. I. KARNATAKA', district: 'BAGALKOT', abbreviation: 'BLK' },
  { subdivision: '', district: 'BELGAUM', abbreviation: 'BEL' },
  { subdivision: '', district: 'BIDAR', abbreviation: 'BDR' },
  { subdivision: '', district: 'BIJAPUR', abbreviation: 'ND' },
  { subdivision: '', district: 'DHARWAD', abbreviation: 'DHA' },
  { subdivision: '', district: 'GADAG', abbreviation: 'GDG' },
  { subdivision: '', district: 'GULBARGA', abbreviation: 'GBG' },
  { subdivision: '', district: 'HAVERI', abbreviation: 'HVR' },
  { subdivision: '', district: 'KOPPAL', abbreviation: 'KPP' },
  { subdivision: '', district: 'RAICHUR', abbreviation: 'RCR' },
  { subdivision: '', district: 'YADGIR', abbreviation: 'YDG' },

  { subdivision: 'ORISSA', district: 'ANUGUL', abbreviation: 'AGL' },
  { subdivision: '', district: 'BALANGIR', abbreviation: 'ND' },
  { subdivision: '', district: 'BALESHWAR', abbreviation: 'ND' },
  { subdivision: '', district: 'BARAGARH', abbreviation: 'BGH' },
  { subdivision: '', district: 'BAUDA', abbreviation: 'ND' },
  { subdivision: '', district: 'BHADRAK', abbreviation: 'BRK' },
  { subdivision: '', district: 'CUTTACK', abbreviation: 'CTK' },
  { subdivision: '', district: 'DEOGARH', abbreviation: 'DGR' },
  { subdivision: '', district: 'DHENKANAL', abbreviation: 'DNK' },
  { subdivision: '', district: 'GAJAPATHI', abbreviation: 'GJP' },
  { subdivision: '', district: 'GANJAM', abbreviation: 'GJM' },
  { subdivision: '', district: 'JAGATSINGHAPUR', abbreviation: 'JSP' },
  { subdivision: '', district: 'JAJAPUR', abbreviation: 'JJP' },
  { subdivision: '', district: 'JHARSUGUDA', abbreviation: 'JSG' },
  { subdivision: '', district: 'KALAHANDI', abbreviation: 'KLH' },
  { subdivision: '', district: 'KANDHAMAL', abbreviation: 'KML' },
  { subdivision: '', district: 'KENDRAPARHA', abbreviation: 'KDP' },
  { subdivision: '', district: 'KENDUJHAR', abbreviation: 'ND' },
  { subdivision: '', district: 'KHORDHA', abbreviation: 'KRD' },
  { subdivision: '', district: 'KORAPUT', abbreviation: 'KRP' },
  { subdivision: '', district: 'MALKANGIRI', abbreviation: 'MKG' },
  { subdivision: '', district: 'MAYURBHANJ', abbreviation: 'MYB' },
  { subdivision: '', district: 'NABARANGAPUR', abbreviation: 'NRP' },
  { subdivision: '', district: 'NAYAGARH', abbreviation: 'NYG' },
  { subdivision: '', district: 'NUAPARHA', abbreviation: 'NPR' },
  { subdivision: '', district: 'PURI', abbreviation: 'PUR' },
  { subdivision: '', district: 'RAYAGARHA', abbreviation: 'RYG' },
  { subdivision: '', district: 'SAMBALPUR', abbreviation: 'SBP' },
  { subdivision: '', district: 'SUBARNAPUR', abbreviation: 'ND' },
  { subdivision: '', district: 'SUNDARGARH', abbreviation: 'SUN' },

  { subdivision: 'PUNJAB', district: 'AMRITSAR', abbreviation: 'ASR' },
  { subdivision: '', district: 'BARNALA', abbreviation: 'BNL' },
  { subdivision: '', district: 'BATHINDA', abbreviation: 'BTD' },
  { subdivision: '', district: 'FARIDKOT', abbreviation: 'FRK' },
  { subdivision: '', district: 'FATEHGARH SAHIB', abbreviation: 'FGS' },
  { subdivision: '', district: 'FIROZPUR', abbreviation: 'FZP' },
  { subdivision: '', district: 'GURDASPUR', abbreviation: 'GDP' },
  { subdivision: '', district: 'HOSHIARPUR', abbreviation: 'HSP' },
  { subdivision: '', district: 'JALANDHAR', abbreviation: 'JLD' },
  { subdivision: '', district: 'KAPURTHALA', abbreviation: 'KPT' },
  { subdivision: '', district: 'LUDHIANA', abbreviation: 'LDN' },
  { subdivision: '', district: 'MANSA', abbreviation: 'MNS' },
  { subdivision: '', district: 'MOGA', abbreviation: 'MGA' },
  { subdivision: '', district: 'MUKTSAR', abbreviation: 'MKS' },
  { subdivision: '', district: 'NAWASHAHR', abbreviation: 'NSR' },
  { subdivision: '', district: 'PATIALA', abbreviation: 'PTL' },
  { subdivision: '', district: 'RUPNAGAR', abbreviation: 'ND' },
  { subdivision: '', district: 'SANGRUR', abbreviation: 'SGR' },
  { subdivision: '', district: 'SAS NAGAR', abbreviation: 'SSM' },
  { subdivision: '', district: 'SBS NAGAR', abbreviation: 'ND' },
  { subdivision: '', district: 'TARN TARAN', abbreviation: 'TTN' },

  { subdivision: 'RAYALASEEMA', district: 'ANANTHAPUR', abbreviation: 'APR' },
  { subdivision: '', district: 'CHITTOOR', abbreviation: 'CHT' },
  { subdivision: '', district: 'CUDDAPAH', abbreviation: 'CDP' },
  { subdivision: '', district: 'KURNOOL', abbreviation: 'KRL' },

  { subdivision: 'S. I. KARNATAKA', district: 'BANGALORE RURAL', abbreviation: 'BLR' },
  { subdivision: '', district: 'BANGLORE URBAN', abbreviation: 'BLU' },
  { subdivision: '', district: 'BELLARY', abbreviation: 'BLY' },
  { subdivision: '', district: 'CHAMARAJANAGAR', abbreviation: 'CRN' },
  { subdivision: '', district: 'CHIKBALLAPUR', abbreviation: 'CBP' },
  { subdivision: '', district: 'CHIKMAGALUR', abbreviation: 'CHK' },
  { subdivision: '', district: 'CHITRADURGA', abbreviation: 'CDG' },
  { subdivision: '', district: 'DAVANGERE', abbreviation: 'DVG' },
  { subdivision: '', district: 'HASSAN', abbreviation: 'HAS' },
  { subdivision: '', district: 'KODAGU', abbreviation: 'KOD' },
  { subdivision: '', district: 'KOLAR', abbreviation: 'KLR' },
  { subdivision: '', district: 'MANDHYA', abbreviation: 'MAN' },
  { subdivision: '', district: 'MYSORE', abbreviation: 'MYS' },
  { subdivision: '', district: 'RAMNAGAR', abbreviation: 'RMN' },
  { subdivision: '', district: 'SHIMOGA', abbreviation: 'SHI' },
  { subdivision: '', district: 'TUMKUR', abbreviation: 'TUM' },

  { subdivision: 'SAURASHTRA & KUTCH', district: 'AMRELI', abbreviation: 'AML' },
  { subdivision: '', district: 'BHAVNAGAR', abbreviation: 'BVN' },
  { subdivision: '', district: 'DIU', abbreviation: 'DIU' },
  { subdivision: '', district: 'JAMNAGAR', abbreviation: 'JMD' },
  { subdivision: '', district: 'JUNAGARH', abbreviation: 'JUN' },
  { subdivision: '', district: 'KACHCHH', abbreviation: 'KTC' },
  { subdivision: '', district: 'PORBANDAR', abbreviation: 'POR' },
  { subdivision: '', district: 'RAJKOT', abbreviation: 'RJT' },
  { subdivision: '', district: 'SURENDRANAGAR', abbreviation: 'SRN' },

  { subdivision: 'SHWB & SIKKIM', district: 'DAKSHIN DINAJPUR', abbreviation: 'SDJ' },
  { subdivision: '', district: 'DARJEELING', abbreviation: 'DJL' },
  { subdivision: '', district: 'EAST', abbreviation: 'EST' },
  { subdivision: '', district: 'JALPAIGURI', abbreviation: 'JPG' },
  { subdivision: '', district: 'KOCHBIHAR', abbreviation: 'ND' },
  { subdivision: '', district: 'MALDA', abbreviation: 'MLD' },
  { subdivision: '', district: 'NORTH', abbreviation: 'NTH' },
  { subdivision: '', district: 'SOUTH', abbreviation: 'STH' },
  { subdivision: '', district: 'UTTAR_DINAJPUR', abbreviation: 'NDJ' },
  { subdivision: '', district: 'WEST', abbreviation: 'WST' },

  { subdivision: 'TAMIL NADU & PUDUCHERRY', district: 'TIRUCHIRAPPALLI', abbreviation: 'ND' },
  { subdivision: '', district: 'TUTICORIN', abbreviation: 'ND' },

  { subdivision: 'TAMILNADU & PONDICHERY', district: 'ARIYALUR', abbreviation: 'ARP' },
  { subdivision: '', district: 'CHENNAI', abbreviation: 'CNI' },
  { subdivision: '', district: 'COIMBATORE', abbreviation: 'CBE' },
  { subdivision: '', district: 'CUDDALORE', abbreviation: 'CUD' },
  { subdivision: '', district: 'DHARAMPURI', abbreviation: 'DPI' },
  { subdivision: '', district: 'DINDIGUL', abbreviation: 'DGL' },
  { subdivision: '', district: 'ERODE', abbreviation: 'ERD' },
  { subdivision: '', district: 'KANCHIPURAM', abbreviation: 'KPM' },
  { subdivision: '', district: 'KANYAKUMARI', abbreviation: 'KYK' },
  { subdivision: '', district: 'KARAIKAL', abbreviation: 'KKL' },
  { subdivision: '', district: 'KARUR', abbreviation: 'KRR' },
  { subdivision: '', district: 'KRISHNAGIRI', abbreviation: 'KGI' },
  { subdivision: '', district: 'MADURAI', abbreviation: 'MDU' },
  { subdivision: '', district: 'MAHE', abbreviation: 'MAE' },
  { subdivision: '', district: 'NAGAPATTINAM', abbreviation: 'NAG' },
  { subdivision: '', district: 'NAMAKKAL', abbreviation: 'NAM' },
  { subdivision: '', district: 'NILGIRI', abbreviation: 'NIL' },
  { subdivision: '', district: 'PERAMBALUR', abbreviation: 'PBR' },
  { subdivision: '', district: 'PUDUCHERY', abbreviation: 'PDY' },
  { subdivision: '', district: 'PUDUKKOTTAI', abbreviation: 'PDK' },
  { subdivision: '', district: 'RAMANATHAPURAM', abbreviation: 'RAM' },
  { subdivision: '', district: 'SALEM', abbreviation: 'SLM' },
  { subdivision: '', district: 'SIVAGANGA', abbreviation: 'SVG' },
  { subdivision: '', district: 'TENI', abbreviation: 'TNI' },
  { subdivision: '', district: 'THANJAVUR', abbreviation: 'TNJ' },
  { subdivision: '', district: 'THIRUVARUR', abbreviation: 'TVR' },
  { subdivision: '', district: 'TIRUNELVELI', abbreviation: 'TNV' },
  { subdivision: '', district: 'TIRUPPUR', abbreviation: 'TPR' },
  { subdivision: '', district: 'TIRUVALLUR', abbreviation: 'TLR' },
  { subdivision: '', district: 'TIRUVANNAMALAI', abbreviation: 'TVM' },
  { subdivision: '', district: 'VELLORE', abbreviation: 'VLR' },
  { subdivision: '', district: 'VILLUPURAM', abbreviation: 'VPM' },
  { subdivision: '', district: 'VIRUDHUNAGAR', abbreviation: 'VRD' },
  { subdivision: '', district: 'YANAM', abbreviation: 'YNM' },

  { subdivision: 'TELANGANA', district: 'ADILABAD', abbreviation: 'ADB' },
  { subdivision: '', district: 'HYDERABAD', abbreviation: 'HYD' },
  { subdivision: '', district: 'KARIMNAGAR', abbreviation: 'KMR' },
  { subdivision: '', district: 'KHAMMAM', abbreviation: 'KMM' },
  { subdivision: '', district: 'MAHABUBNAGAR', abbreviation: 'MBR' },
  { subdivision: '', district: 'MEDAK', abbreviation: 'MDK' },
  { subdivision: '', district: 'NALGONDA', abbreviation: 'NGD' },
  { subdivision: '', district: 'NIZAMABAD', abbreviation: 'NZD' },
  { subdivision: '', district: 'RANGA REDDY', abbreviation: 'RGY' },
  { subdivision: '', district: 'WARANGAL', abbreviation: 'WRL' },

  { subdivision: 'UTTARAKHAND', district: 'ALMORA', abbreviation: 'AMR' },
  { subdivision: '', district: 'BAGESHWAR', abbreviation: 'BGW' },
  { subdivision: '', district: 'CHAMOLI', abbreviation: 'CML' },
  { subdivision: '', district: 'CHAMPAWAT', abbreviation: 'CPT' },
  { subdivision: '', district: 'DEHRADUN', abbreviation: 'DDN' },
  { subdivision: '', district: 'HARIDWAR', abbreviation: 'HRD' },
  { subdivision: '', district: 'NANITAL', abbreviation: 'NNT' },
  { subdivision: '', district: 'PAURI GARHWAL', abbreviation: 'PGL' },
  { subdivision: '', district: 'PITHORAGARH', abbreviation: 'PRG' },
  { subdivision: '', district: 'RUDRAPRAYAG', abbreviation: 'RPG' },
  { subdivision: '', district: 'TEHRI GARWAL', abbreviation: 'TGL' },
  { subdivision: '', district: 'UDHAM SINGH NAGAR', abbreviation: 'UDS' },
  { subdivision: '', district: 'UTTARKASHI', abbreviation: 'UKS' },

  { subdivision: 'VIDARBHA', district: 'AKOLA', abbreviation: 'AKL' },
  { subdivision: '', district: 'AMARAVATI', abbreviation: 'AMT' },
  { subdivision: '', district: 'BHANDARA', abbreviation: 'BND' },
  { subdivision: '', district: 'BULDHANA', abbreviation: 'BLD' },
  { subdivision: '', district: 'CHANDRAPUR', abbreviation: 'CPR' },
  { subdivision: '', district: 'GADCHIROLI', abbreviation: 'GDL' },
  { subdivision: '', district: 'GONDIYA', abbreviation: 'GNA' },
  { subdivision: '', district: 'NAGPUR', abbreviation: 'NGP' },
  { subdivision: '', district: 'WARDHA', abbreviation: 'WDH' },
  { subdivision: '', district: 'WASHIM', abbreviation: 'WSM' },
  { subdivision: '', district: 'YAVATMAL', abbreviation: 'YTL' },

  { subdivision: 'WEST MADHYA PRADESH', district: 'ALIRAJPUR', abbreviation: 'ALP' },
  { subdivision: '', district: 'ASHOKNAGAR', abbreviation: 'AKN' },
  { subdivision: '', district: 'BARWANI', abbreviation: 'BRW' },
  { subdivision: '', district: 'BETUL', abbreviation: 'BTL' },
  { subdivision: '', district: 'BHIND', abbreviation: 'BHD' },
  { subdivision: '', district: 'BHOPAL', abbreviation: 'BPL' },
  { subdivision: '', district: 'BURHANPUR', abbreviation: 'BHP' },
  { subdivision: '', district: 'DATIA', abbreviation: 'DTA' },
  { subdivision: '', district: 'DATIA', abbreviation: 'DTA' },
  { subdivision: '', district: 'DATIA', abbreviation: 'DTA' },
  { subdivision: '', district: 'DEWAS', abbreviation: 'DWS' },
  { subdivision: '', district: 'DHAR', abbreviation: 'DHR' },
  { subdivision: '', district: 'EAST NIMAR', abbreviation: 'ND' },
  { subdivision: '', district: 'GUNA', abbreviation: 'GUN' },
  { subdivision: '', district: 'GWALIOR', abbreviation: 'GLR' },
  { subdivision: '', district: 'HARDA', abbreviation: 'HAR' },
  { subdivision: '', district: 'HOSHANGABAD', abbreviation: 'HSB' },
  { subdivision: '', district: 'INDORE', abbreviation: 'IDR' },
  { subdivision: '', district: 'JHABUA', abbreviation: 'JBA' },
  { subdivision: '', district: 'MANDSAUR', abbreviation: 'MDS' },
  { subdivision: '', district: 'MORENA', abbreviation: 'MRN' },
  { subdivision: '', district: 'NIMACH', abbreviation: 'NMC' },
  { subdivision: '', district: 'RAISEN', abbreviation: 'RSN' },
  { subdivision: '', district: 'RAJGARH', abbreviation: 'RJG' },
  { subdivision: '', district: 'RATLAM', abbreviation: 'RTM' },
  { subdivision: '', district: 'SEHORE', abbreviation: 'SEH' },
  { subdivision: '', district: 'SHAJAPUR', abbreviation: 'SJP' },
  { subdivision: '', district: 'SHEOPUR', abbreviation: 'SOP' },
  { subdivision: '', district: 'SHIVPURI', abbreviation: 'SVP' },
  { subdivision: '', district: 'UJJAIN', abbreviation: 'UJN' },
  { subdivision: '', district: 'VIDESHA', abbreviation: 'VDS' },
  { subdivision: '', district: 'WEST NIMAR', abbreviation: 'ND' },

  { subdivision: 'WEST RAJASTHAN', district: 'BARMER', abbreviation: 'BRM' },
  { subdivision: '', district: 'BIKANER', abbreviation: 'BKN' },
  { subdivision: '', district: 'CHURU', abbreviation: 'CRU' },
  { subdivision: '', district: 'GANGANAGAR', abbreviation: 'GGN' },
  { subdivision: '', district: 'HANUMANGARH', abbreviation: 'HAN' },
  { subdivision: '', district: 'JAISELMER', abbreviation: 'JSM' },
  { subdivision: '', district: 'JALOR', abbreviation: 'JLR' },
  { subdivision: '', district: 'JODHPUR', abbreviation: 'JDP' },
  { subdivision: '', district: 'NAGAUR', abbreviation: 'NGR' },
  { subdivision: '', district: 'PALI', abbreviation: 'PLI' },

  { subdivision: 'WEST UTTAR PRADESH', district: 'AGRA', abbreviation: 'AGR' },
  { subdivision: '', district: 'ALIGARH', abbreviation: 'ALG' },
  { subdivision: '', district: 'AURAIYA', abbreviation: 'AUR' },
  { subdivision: '', district: 'BADAUN', abbreviation: 'BAD' },
  { subdivision: '', district: 'BAGHPAT', abbreviation: 'BGT' },
  { subdivision: '', district: 'BAREILLY', abbreviation: 'BRL' },
  { subdivision: '', district: 'BIJNOR', abbreviation: 'BJN' },
  { subdivision: '', district: 'BULANDSAHAR', abbreviation: 'BLS' },
  { subdivision: '', district: 'ETAH', abbreviation: 'ETA' },
  { subdivision: '', district: 'ETAWAH', abbreviation: 'ETW' },
  { subdivision: '', district: 'FIROZABAD', abbreviation: 'FIR' },
  { subdivision: '', district: 'GAUTAMBUDHNAGAR', abbreviation: 'GBN' },
  { subdivision: '', district: 'GHAZIABAD', abbreviation: 'GZA' },
  { subdivision: '', district: 'HAMIRPUR', abbreviation: 'ND' },
  { subdivision: '', district: 'JALAUN', abbreviation: 'JAL' },
  { subdivision: '', district: 'JHANSI', abbreviation: 'JNS' },
  { subdivision: '', district: 'JYOTIBAPHULE NAGAR', abbreviation: 'JPN' },
  { subdivision: '', district: 'KANSHIRAMNAGAR', abbreviation: 'KSR' },
  { subdivision: '', district: 'LALITPUR', abbreviation: 'LLP' },
  { subdivision: '', district: 'MAHAMAYANAGAR', abbreviation: 'MMN' },
  { subdivision: '', district: 'MAHOBA', abbreviation: 'MHB' },
  { subdivision: '', district: 'MAINPURI', abbreviation: 'MAI' },
  { subdivision: '', district: 'MATHURA', abbreviation: 'MTR' },
  { subdivision: '', district: 'MEERUT', abbreviation: 'MRT' },
  { subdivision: '', district: 'MORADABAD', abbreviation: 'MRD' },
  { subdivision: '', district: 'MUZAFARNAGAR', abbreviation: 'MZN' },
  { subdivision: '', district: 'PILHIBHIT', abbreviation: 'PIL' },
  { subdivision: '', district: 'RAMPUR', abbreviation: 'RMP' },
  { subdivision: '', district: 'SHAHJAHANPUR', abbreviation: 'SJR' },
  { subdivision: '', district: 'SHARANPUR', abbreviation: 'SHP' }

]
}